version: '3'
env:
  JEKYLL_ENV: '{{.JEKYLL_ENV | default "production" }}'

tasks:
  build:
    cmds:
      - rvm ruby-3.3.6 exec bundle exec jekyll build

  collect:
    cmds:
      - zsh bin/collect.sh

  convert:
    cmds:
      - zsh bin/convert.sh

  create:
    cmds:
      - zsh bin/create.sh

  drafts:
    cmds:
      - rvm ruby-3.3.6 exec bundle exec jekyll serve --port 10000 --drafts {{.CLI_ARGS}}

  publish:
    cmds:
      - rvm ruby-3.3.6 exec zsh bin/publish.sh

  start:
    cmds:
      - rvm ruby-3.3.6 exec bundle exec jekyll serve --port 9000 {{.CLI_ARGS}}
