---
layout: post
title: Minikube with hyperkit
date: 2021-03-29 07:29 +0200
last_updated: 2021-03-29 07:29 +0200
author: Christoph Kappel
tags: minikube hyperkit virtualbox dns macos
categories: cloud
toc: false
---
:1: https://github.com/moby/hyperkit
:2: https://kubernetes.io/
:3: https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection
:4: https://www.virtualbox.org/
:5: https://coredns.io/
:6: https://developer.apple.com/bonjour/

I cannot really say what happened, but unfortunately during some of the latest updates
DNS resolution inside of my {1}[Hyperkit] VM stopped working.
I can manually set the DNS to something like `8.8.8.8`, but after a while it fails again.

After some digging around I found this:

<https://github.com/kubernetes/minikube/issues/3036>

Looks like a local running DNS server for the Bonjour handler clashes with {5}[CoreDNS] and
results in a non-working DNS configuration inside of {2}[Kubernetes]. That leads to various issues,
but formost problems to fetch any container from docker and the likes.

Surely there are lots of arcane solutions, one of my favorite is to disable the
{3}[System Integrity Protection] and the [6][Bonjour] system. Since I don't want
to deal with all the consequences of it yet, there should be another way I can approach.

== Conclusion

Alas, the solution is pretty easy:
Just don't use {1}[HyperKit] and switch to {4}[Virtualbox].