---
layout: post
title: Idiosyncrasy of the Docker CLI
date: 2021-07-23 10:53 +0200
last_updated: 2021-07-23 10:53 +0200
tags: tools docker cli quarkus kafka redpanda
categories: tech
toc: false
---
Although I use {1}[Docker] on a daily basis, I never really got into its CLI. Most of the time I am
just baffled how complex it is to get really simple things done.

Just to set up the stage (I plan on writing a detailed post about {3}[Redpanda]):

During my experiments with the latest {2}[Quarkus] version, I stumbled upon a faster replacement
for {5}[Kafka], which is either used as a default {4}[devservice] now or some default of
{6}[Kogito].

A {4}[devservices] you might be wondering? Without going much into detail, it is basically an
integration of  {7}[Testcontainers] to start required infrastructure services like a database for
testing in {1}[Docker]. {4}[Devservices] also take care of the config, so all the required mapping
is set automatically.

To configure {3}[Redpanda], I need to know the exposed port to connect to and the
{7}[Testcontainers] integration prints it dutifully to the log though:

====== **Log**:
[source,log]
----
2021-07-23 07:48:44,130 INFO  [io.qua.kaf.cli.dep.DevServicesKafkaProcessor] (build-38) Dev Services for Kafka started. Start applications that need to use the same Kafka broker using -Dkafka.bootstrap.servers=PLAINTEXT://localhost:55002
----

This is still no option for custom scripts or in any way convenient.

== Docker CLI

{1}[Docker] comes with a CLI as you probably know. After some digging into and a pinch of despair,
mapping of image name to the actual container is quite complicated. For my taste it takes way too
many calls to different shell tools, which probably is not portable, but it can be done with
{8}[port] and {9}[inspect]:
 
====== **Shell**:
[source,shell]
----
$ docker port $(docker ps | grep redpanda | awk '{print $1}') | grep -m 1 9092 | cut -d ':' -f 2
----

Another thing I probably just lack experience with, is the format string. I am quite sure
this is just awesome for any seasoned {10}[Go] developer and it is basically everywhere from there
starting with supporting tools like {11}[Helm] or the foundation of the cloud itself,
{12}[Kubernetes].

So if the next example is pretty straight forward to you have fun with it, I am in a corner reading
specs:

====== **Shell**:
[source,shell]
----
{% raw %}$ docker inspect --format='{{(index (index .NetworkSettings.Ports "9092/tcp") 0).HostPort}}' $(docker ps --format "{{.ID}}" --filter="ancestor=vectorized/redpanda:v21.5.5"){% endraw %}
----

:1: https://docker.com
:2: https://quarkus.io
:3: https://github.com/vectorizedio/redpanda
:4: https://quarkus.io/guides/dev-services
:5: https://kafka.apache.org/
:6: https://kogito.kie.org/
:7: https://www.testcontainers.org/
:8: https://docs.docker.com/engine/reference/commandline/inspect/
:9: https://docs.docker.com/engine/reference/commandline/port/
:10: https://golang.org/
:11: https://helm.sh/
:12: https://kubernetes.io/