---
layout: post
title: One month of Podman
description: This blog post is a followup to my experience with Podman during the first month.
date: 2021-12-28 22:45 +0100
last_updated: 2022-07-05 16:00 +0100
author: Christoph Kappel
tags: docker podman jaeger quarkus opentracing opentelemetry gelf fluentd showcase
categories: tools
toc: true
---
:source-highlighter: highlight.js

:1: https://podman.io/getting-started/network
:2: https://en.wikipedia.org/wiki/Cgroups
:3: https://www.jaegertracing.io/docs/1.29/deployment/#collector
:4: https://docs.docker.com/compose/
:5: https://docker.com
:6: https://www.fluentd.org/
:7: https://github.com/junegunn/fzf
:8: https://www.graylog.org/features/gelf
:9: https://pkg.go.dev/github.com/containers/gvisor-tap-vsock/cmd/gvproxy
:10: https://hub.docker.com/r/jaegertracing/all-in-one
:11: https://www.jaegertracing.io/docs/1.29/deployment/#collector
:12: https://www.jaegertracing.io/
:13: https://en.wikipedia.org/wiki/Linux
:14: https://en.wikipedia.org/wiki/MacOS
:15: https://hub.docker.com/r/jaegertracing/opentelemetry-all-in-one/
:16: https://opentelemetry.io/
:17: https://opentracing.io/
:18: https://github.com/open-telemetry/opentelemetry-collector
:19: https://podman.io/
:20: https://developers.redhat.com/blog/2019/01/15/podman-managing-containers-pods
:21: https://quarkus.io/
:22: https://github.com/rootless-containers/slirp4netns
:23: https://github.com/open-telemetry/opentelemetry-collector/discussions/2558
:24: https://en.wikipedia.org/wiki/Tracing_(software)
:25: https://github.com/unexist/showcase-logging-vs-tracing-quarkus

In my previous post [Migrating to Podman]({% post_url 2021-12-01-migrating-to-podman %}) you
basically accompanied me on my migration from a {4}[docker-compose] file to a more CLI-based
approach with {19}[Podman].
I am still working on my {25}[logging-vs-tracing] showcase, but there were a few surprises and I
just wanted to write a follow-up instead of just modifying my original post.

== Container ports

I originally started with {17}[OpenTracing], but while I was trying to figure everything out the
{21}[Quarkus] project finally made the switch to {16}[OpenTelemetry] and I had to start again. I am
going to explain **how** in my next post, so let us just accept the fact that {16}[OpenTelemetry]
needs another {3}[collector] which has to be added to my setup.

Adding another container is no problem, but when I tried to fire it up I found this in the logs:

[source,log]
----
Error: cannot setup pipelines: cannot start receivers: listen udp :6832: bind: address already in
use
----

The apparent problem here is that both the {11}[jaeger-collector] and the {18}[otel-collector] run
on the same port.
To my surprise, there is no network separation of the containers inside of a {20}[pod] (by default),
but after some headaches to be expected. When you publish a port it also just works on
{20}[pod]-level for **rootless**.

== Networking between pods

I spent some hours trying to figure out, if I can just disable this port either for the
{11}[jaeger-collector] or the {18}[otel-collector], but to no avail. Desperate as I was, I just
moved both collectors to different {20}[pod] and considered it done.

This was, when I discovered how my networking really worked: Although I can access the published
ports from my host machine, the application inside of the container inside of a {20}[pod] cannot.

Possible solutions that I came up with:

1. Switch the {20}[pod] network from {1}[bridge] to {22}[sirp4netns] mode and find solutions for
all newly introduced problems.
2. Move from {10}[jaeger-all-in-one] to the standalone versions of each component.
(There is also {15}[opentelemetry-all-in-one] version, but according to {23}[this] post it has
been discontinued.)
3. Start {12}[Jaeger] first and just hope it doesn't complain.

Yes, I went the obvious way and just started {12}[Jaeger] first, worked like a charm..

== No support for UDP yet

{24}[Tracing] finally running, I discoverd that my {21}[Quarkus] instances couldn't connect to
{6}[Fluentd] on port 12201 anymore:

[source,log]
----
LogManager error of type GENERIC_FAILURE: Port localhost:12201 not reachable
----

The problem here is that I configured {6}[Fluentd] to expect {8}[gelf] messages there and
absolutely had no clue about the message format.
I found this handy shell script as a gist, kudos to the author:

<https://gist.github.com/gm3dmo/7721379>

With it, I could verify two things:

1. I couldn't reach {6}[Fluentd] from my host machine.
2. And inside of the container everything worked fine.

Some hours later I stumbled upon this:

<https://issueexplorer.com/issue/containers/podman-machine-cni/8>

This pretty much explained all my problems: Currently {9}[gvproxy] has no support for udp and just
ignores the udp flag altogether.
My instances were expecting udp, all they got was tcp and this ultimately failed.

The easiest solution here was to configure {8}[gelf] to run on tcp, which both the input plugin
and in the {8}[gelf] handler of {21}[Quarkus] support.
I don't want to bore you with the troubles I had to find the correct config option, so I will just
point you to the source code:

<https://github.com/MerlinDMC/fluent-plugin-input-gelf/blob/master/lib/fluent/plugin/in_gelf.rb>

== Access to local filesystems

{19}[Podman] needs the {2}[cgroups] feature from {13}[Linux] to properly run your containers and
since {14}[macOS] doesn't support this natively, some kind of virtualization is used a a workaround.

This virtualization causes problems, when the container shim expects paths inside of the guest
machine to be the same as on the underlying host machine.

To bypass this, {5}[Docker] automatically mounts the user home into the guest machine, so all access
can be done like the container runs on the same host.

{19}[Podman] doesn't mount your home automatically, but can be forced to when you init your machine
like this:

[source,shell]
----
podman machine init -v $HOME:$HOME
----

== Conclusion

I had some problems getting warm with {19}[Podman], but since I've sorted this out it works like a
charm.
I've created even more scripts to make the usage for me easier - with the help of {7}[fzf], ofc.

I know I don't have to remind you, but my logging-vs-tracing showcase can still be found here:

<https://github.com/unexist/showcase-logging-vs-tracing-quarkus>