---
layout: post
title: Big Data formats
date: %%%DATE%%%
last_updated: %%%DATE%%%
author: Christoph Kappel
tags: showcase
categories: showcase big.data
toc: true
---
:imagesdir: /assets/images/big-data-formats
:figure-caption!:
:table-caption!:

Usually when I start a new blog post, I want to mention hundreds of things tightly intermixed
with each other and totally miss the scope of the things I originally wanted to cover.

NOTE: This is actually the funny part of writing and a great way of learning how to define an outline
**and** also stay within of it.

Needless to say exactly happened in my post about [Big Data][], which I am trying to complete for
quite some time.
This time I am only partly guilty, because the whole topic is really huge and it **is** difficult
to include just the necessities of the topic.

One way to deal with these kind of problems is either to reduce the overall scope or just split
things from the main article into smaller and more focused ones.

So in this article let us talk in preparation about two heavily used formats in the Big Data world,
which I didn't know in depth at time of writing the post about [evolving a format][].

== New formats

=== Iceberg

=== Parquet

== Conclusion