---
layout: post
title: Documenting shellscripts
description: TBD
#date: %%%DATE%%%
#last_updated: %%%DATE%%%
author: Christoph Kappel
tags: showcase
categories: tech
toc: true
---
ifdef::asciidoctorconfigdir[]
:imagesdir: {asciidoctorconfigdir}/../assets/images/documenting_shellscripts
endif::[]
ifndef::asciidoctorconfigdir[]
:imagesdir: /assets/images/documenting_shellscripts
endif::[]
:figure-caption!:
:table-caption!:
:page-liquid:

:bats: https://github.com/bats-core/bats-core
:shunit: https://github.com/kward/shunit2
:confluence: https://www.atlassian.com/software/confluence
:doxygen: https://doxygen.nl/
:commands: https://doxygen.nl/manual/commands.html

If you have a look at the typical posts in this blog you will see quite a few about documenting
stuff.
In fact there are so many, I am kind of surprised by myself that I've found another piece I'd like
to demonstrate.

Actually I've thought shellscripts aren't the stuff you'd expect to see in a general documentation,
but then there are projects like {bats}[Bats] and {shunit}[Shunit2].
So when some people even spend time to write complete test harnesses to keep everything at bay,
we, you and I, probably don't have to feel guilty if we proceed here.

== Why?

Lately, I am working on a monitoring script, which to everyone's surprise, exploded
feature-creepy-wise and I had to rename/split it several times, just to limit the collateral
damage.

And as the eager adept of writing documentation-as-code that I am, I carefully drafted all
documentation into the living body of the scripts and honed it to perfection.
Unfortunately and I've probably probably mentioned in dozen of times in every other post here,
there is always the problem to provide the right type of documentation, to the right audience at
the right place.

So much work shoudln't be for naught, so behold, we are going to learn in this post how we can move
shellscript documentation from our repository to {confluence}[Confluence]footnote:[Yes, I KNOW!] and
put it to rest.

Are you up to this adventure?

== Doxygen all the things

{doxygen}[Doxygen] is generally a good starting point for every documentation approach, especially
when the targeted language is among the supported languages of the project.

Doxygen offers easy to understand {commands}[commands] to properly describe variables, functions
bodies and also complete files with every copyleft and `$ID$` information of your heart's desire.

The basic format looks as easy as this:

[source,c]
----
 /** main
  * @brief Main function
  *
  * @details
  * @startuml
  * main.c -> lang.c : get_lang()
  * @enduml
  *
  * @param[in]  argc  Number of arguments
  * @param[in]  argv  Array with passed commandline arguments
  * @retval  0  Default return value
  **/

 int main(int argc, char *argv[]) {

    printf("Hello, %s", get_lang("NL"));

    return 0;
 }
----


== Preprocessing from hell

== Grande finale

== Conclusion

All examples can be found here:

<https://github.com/unexist/showcase-documentation-asciidoxy>

[bibliography]
== Bibliography
