---
layout: post
title: Documenting shellscripts
description: TBD
#date: %%%DATE%%%
#last_updated: %%%DATE%%%
author: Christoph Kappel
tags: showcase
categories: tech
toc: true
---
ifdef::asciidoctorconfigdir[]
:imagesdir: {asciidoctorconfigdir}/../assets/images/documenting_shellscripts
endif::[]
ifndef::asciidoctorconfigdir[]
:imagesdir: /assets/images/documenting_shellscripts
endif::[]
:figure-caption!:
:table-caption!:
:page-liquid:

:bats: https://github.com/bats-core/bats-core
:shunit: https://github.com/kward/shunit2
:confluence: https://www.atlassian.com/software/confluence


If you have a look at the typical posts in this blog you will see quite a few about documenting
stuff.
In fact there are so many, I am kind of surprised by myself that I've found another piece I'd like
to demonstrate.

Actually I've thought shellscripts aren't the stuff you'd expect to see in a general documentation,
but then there are projects like {bats}[Bats] and {shunit}[Shunit2].
So when some people even spend time to write complete test harnesses to keep everything at bay,
we, you and I, probably don't have to feel guilty.

== Why?

Lately, I am working on a monitoring script, which to everyone's surprise exploded feature-wise and
I had to rename/split it several times, just to limit the collateral damage.

I am an eager adept of writing documentation(-as-code) directly into the files, but like I've
probably mentioned in every other post here, there is always the problem to provide the right type
of documentation, to the right audience at the right place.

So since everybody should be able to read our carefully drafted and honed docs, we are going to
learn in this post how we can move shellscript documentation to
{confluence}[Confluence]footnote:[Yes, I KNOW!] to [line-through]#die# rest.

Are you up to this adventure?

== Doxygen all the things

== Preprocessing from hell

== Grande finale

== Conclusion

All examples can be found here:

<https://github.com/unexist/showcase->

[bibliography]
== Bibliography
