---
layout: post
title: Domain storytelling
description: This blog post introduces domain storytelling as an easy and interactive way of conveying use-cases with strong ties to domain-driven design.
#date: %%%DATE%%%
#last_updated: %%%DATE%%%
author: Christoph Kappel
tags: ddd diagrams uml
categories: communication
toc: true
---
ifdef::asciidoctorconfigdir[]
:imagesdir: {asciidoctorconfigdir}/../assets/images/domain_storytelling
endif::[]
ifndef::asciidoctorconfigdir[]
:imagesdir: /assets/images/domain_storytelling
endif::[]
:figure-caption!:
:table-caption!:
:page-liquid:

```
https://domainstorytelling.org
https://egon.io/
https://en.wikipedia.org/wiki/Curse_of_knowledge
```

[quote,William H. Whyte]
The great enemy of communication is the illusion of it.

I think we can all agree on communication is hard and especially when you want to convey something
that is perfectly clear to you.
One simple explanation can be the [curse of knowledge][], but this doesn't help me (at least) on my
next struggle to find the right words without getting frustrated first.

This kind of struggle can be mildly said interesting in most cases during personal communication,
but what happens during anything related to business, like complex requirement of your next big
product?

During the course of this post I want to put emphasis on visual communication, which can help to
support any narrativ and ultimately provide additional help in getting understood.

TIP: Like many posts in this blog before, we again use my sample todo application - if you still
haven't seen it yet you can find an [OpenAPI][] specification here:
<https://blog.unexist.dev/redoc/#tag/Todo>¬

== Simple use-cases


****
A user wants to create a new todo entry.
****

.Simple use-case
//++++
//{% plantuml %}
//!theme unexist from {{ site.asciidoctor_attributes.plantumldir }}
[plantuml]
----
skinparam linetype ortho
skinparam nodesep 20
skinparam ranksep 20

@startuml
:User: --> (Create todo)/
@enduml
----
//{% endplantuml %}
//++++

.Technical use-case
//++++
//{% plantuml %}
//!theme unexist from {{ site.asciidoctor_attributes.plantumldir }}
[plantuml]
----
skinparam linetype ortho
skinparam nodesep 20
skinparam ranksep 20

@startuml
:User: --> (Create todo)/

json Todo {
    "title": "New todo",
    "description": "Write a blog post"
}
@enduml
----
//{% endplantuml %}
//++++

== Domain-stories

== Conclusion

All examples can be found here:

<https://github.com/unexist/showcase->

[bibliography]
== Bibliography

* [[[domstory]]] Stefan Hofer, Henning Schwentner, Domain Storytelling: A Collaborative, Visual and Agile Way to Build Domain-Driven Software, Addison-Wesley 2021
* [[[viscom]]] Jacqui Read, Communication Patterns: A Guide for Developers and Architects, O'Reilly 2023
