---
layout: post
title: Domain storytelling
description: This blog post introduces domain storytelling as an easy and interactive way of conveying use-cases with strong ties to domain-driven design.
#date: %%%DATE%%%
#last_updated: %%%DATE%%%
author: Christoph Kappel
tags: ddd diagrams uml
categories: communication
toc: true
---
ifdef::asciidoctorconfigdir[]
:imagesdir: {asciidoctorconfigdir}/../assets/images/domain_storytelling
endif::[]
ifndef::asciidoctorconfigdir[]
:imagesdir: /assets/images/domain_storytelling
endif::[]
:figure-caption!:
:table-caption!:
:page-liquid:

```
https://domainstorytelling.org
https://egon.io/
https://en.wikipedia.org/wiki/Curse_of_knowledge
https://ifvp.org/content/why-our-brain-loves-pictures
https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=visual+perception&btnG=&oq=visual+perc
```

[quote,William H. Whyte]
The great enemy of communication is the illusion of it.

I think we can all agree on communication is hard and especially when you want to convey something
that is perfectly clear to you.
One simple explanation can be the [curse of knowledge][], but this doesn't help me (at least) on my
next struggle to find the right words without getting frustrated first.

This kind of struggle can be mildly said interesting in most cases during personal communication,
but what happens during anything related to business, like complex requirement of your next big
product?

During the course of this post I want to put emphasis on visual communication, which can help to
support any narrativ and ultimately provide additional help in getting understood.

TIP: Like many posts in this blog before, we again use my sample todo application - if you still
haven't seen it yet you can find an [OpenAPI][] specification here: +
<https://blog.unexist.dev/redoc/#tag/Todo>

== Simple use-cases

Even with business requirements it is possible to start simple and one of the simplest things a
user probably wants to do with our application is following:

****
A user wants to create a new todo entry.
****

Simple enough and perfectly straight forward, but the same can be expressed (and supported not
replaced mind you) with a simple use-case diagram:

.Simple use-case
//++++
//{% plantuml %}
//!theme unexist from {{ site.asciidoctor_attributes.plantumldir }}
[plantuml]
----
skinparam linetype ortho
skinparam nodesep 20
skinparam ranksep 20

@startuml
:User: --> (Create todo)/
@enduml
----
//{% endplantuml %}
//++++

I suppose if I'd ask you for your first thoughts on this example now I'd probably get something in
the  range of this just adds clutter and is completely overkill for this really simple matter.

So still why do I insist this adds benefits?

=== Excursion: Visual perception

We humans are [really good in visual perception] and a lot of information is gathered that way in
literally a glimpse.

You can easily verify it on your own:
How long does it take to read the single requirement vs how long do you have to look at the picture?

NOTE: There are so many sources to cite from, if you are curious about this whole topic please
give [Google Scholar][] a spin, but going further probably leads away from the point I want to make.

=== Technical use-cases

Targeting the right audience is also key here, but still adding too much technical jargon and
information to a use-case kind of beats the benefit of getting everything in a quick glance.

[UML][] might offer many niceties, but please ask yourself does the extension of the previous
use-case add anything of value?

.Technical use-case
//++++
//{% plantuml %}
//!theme unexist from {{ site.asciidoctor_attributes.plantumldir }}
[plantuml]
----
skinparam linetype ortho
skinparam nodesep 20
skinparam ranksep 20

@startuml
actor User << User >> as u1

rectangle "Create todo" {
    (Handle REST) as uc1
    (Persist data) as uc2
}

note "JSON Todo" as n1
u1 --> n1
n1 --> uc1

uc1 --> uc2

json Todo {
    "title": "New todo",
    "description": "Write a blog post"
}
@enduml
----
//{% endplantuml %}
//++++

Let's move on to a more complex use-case.

== Advanced use-cases

****
An admin want to define a list of swear words. +
A user wants to create a new todo entry free of swearwords.
****

.Advanced use-case
//++++
//{% plantuml %}
//!theme unexist from {{ site.asciidoctor_attributes.plantumldir }}
[plantuml]
----
skinparam linetype ortho
skinparam nodesep 20
skinparam ranksep 20

@startuml
:Admin: --> (Limit Swearwords)/
:User: --> (Create todo)/
(Create todo)/ --> (Swearword check)/ : <<uses>>
(Swearword check) ..> :User: : Todo denied
@enduml
----
//{% endplantuml %}
//++++

== Domain-stories

== Conclusion

All examples can be found here:

<https://github.com/unexist/showcase->

[bibliography]
== Bibliography

* [[[domstory]]] Stefan Hofer, Henning Schwentner, Domain Storytelling: A Collaborative, Visual and Agile Way to Build Domain-Driven Software, Addison-Wesley 2021
* [[[viscom]]] Jacqui Read, Communication Patterns: A Guide for Developers and Architects, O'Reilly 2023
