---
layout: post
title: Embedding other languages
description: TBD
#date: %%%DATE%%%
#last_updated: %%%DATE%%%
author: Christoph Kappel
tags: showcase
categories: tech
toc: true
---
ifdef::asciidoctorconfigdir[]
:imagesdir: {asciidoctorconfigdir}/../assets/images/embedding_other_languages
endif::[]
ifndef::asciidoctorconfigdir[]
:imagesdir: /assets/images/embedding_other_languages
endif::[]
:figure-caption!:
:table-caption!:
:page-liquid:

:deskbar: https://sourceforge.net/projects/deskbar/
:subtle: https://github.com/unexist/subtle
:subtle-rs: https://github.com/unexist/subtle-rs
:touchjs: https://github.com/unexist/touchjs
:rubtle: https://github.com/unexist/rubtle
:extism: https://extism.org/
:wasm: https://webassembly.org/
:lua: https://www.lua.org/
:ruby: https://www.ruby-lang.org/en/
:foss: https://en.wikipedia.org/wiki/Free_and_open-source_software
:github: https://github.com/
:codeberg: https://codeberg.org/

Coming up with a new software project is always a fun thing.
You start from a mere idea, like some quality-of-life thing as replacement for a piece of software that drives you nuts
or even something that addresses a real problem, you tinker with it, play with it and move on.
And *if* everything goes really well you might end up with something quite usable.

This is by itself a great milestone, but wouldn't it be really great, if other people can also enjoy it?
Living in a {FOSS}[FOSS] world publishing your code on
{Github}[Github]footnote:[Or {Codeberg}[Codeberg], if you don't want to contribute to AI]  is just a stone throw away


== Barebone

== Scripting languages

== Webassembly

== Conclusion

The list of examples is quite long, but please help yourself:

- <{deskbar}>
- <{subtle}>
- <{subtle-rs}>
- <{touchjs}>
- <{rubtle}>

[bibliography]
== Bibliography
