---
layout: post
title: The many facets of domain-driven design
description: TBD
#date: %%%DATE%%%
#last_updated: %%%DATE%%%
author: Christoph Kappel
tags: ddd
categories: software-design myself
toc: true
---
Discovering [domain-driven design][] has been an interesting journey for me.
Over the course of the last fives years I discovered more and more different facets of it and I am
still amazed how this model helps to understand me to different old and new domain contexts.

This in this more theoretical blog post I want to talk about the different phases and facets and
also lay out what has been the real benefit for me.

== Tactically and strategically?

== Where is the framework?

== Inside and outside of bounded contexts

== Discovering old and new

== Conclusion

[bibliography]
== Bibliography

* [[[ddd]]] Eric Evans, Domain-Driven Design: Tackling Complexity in the Heart of Software, Addison-Wesley Professional 2003
* [[[implddd]]] Vernon Vaughn, Matei Zaharia, Implementing Domain-Driven Design, Addison-Wesley Professional 2013
* [[[learnddd]]] Vladik Khononov, Learning Domain-Driven Design: Aligning Software Architecture and Business Strategy, O'Reilly 2021
* [[[patternsddd]]] Scott Millett, Nick Tune, Patterns Principles and Practices of Domain Driven Design, Wrox 2015
* [[[eventstorm]]] Alberto Brandolini, Introducing EventStorming, LeanPub 2015
* [[[storytelling]]] Henning Schwentner, Stefan Hofer , Domain Storytelling: A Collaborative, Visual, and Agile Way to Build Domain-Driven Software, Addison-Wesley Professional 2021

----
https://martinfowler.com/bliki/UbiquitousLanguage.html
https://egon.io
----