---
layout: post
title: Gitlab with Podman
description: TBD
#date: %%%DATE%%%
#last_updated: %%%DATE%%%
author: Christoph Kappel
tags: gitlab podman showcase
categories: cicd
toc: true
---
ifdef::asciidoctorconfigdir[]
:imagesdir: {asciidoctorconfigdir}/../assets/images/gitlab_with_podman
endif::[]
ifndef::asciidoctorconfigdir[]
:imagesdir: /assets/images/gitlab_with_podman
endif::[]
:figure-caption!:
:table-caption!:

////
https://docs.gitlab.com/omnibus/settings/memory_constrained_envs.html
////

== Gitlab with Podman

My ultimate goal for my previous post was to demonstrate the combination of [Gitlab][], [Podman][]
and [Dagger][], but unfortunately I ran into so many different problems I made the decision to
break it apart.

This is second part of the small series and explains how to set up Gitlab with Podman-in-Podman
and various pitfalls on the way.

NOTE: If you are looking for the first part just follow this link over here:
<https://unexist.blog/cicd/2024/05/05/building-with-dagger.html>

=== Setting everything up

The first step is to start Gitlab itself and this requires a SSL cert - so just to make this
a lot more interesting we create a self-signed one:

[source,shell]
----
$ openssl req -newkey rsa:4096 -x509 -sha512 -days 365 -nodes \
    -out gitlab.crt -keyout gitlab.key \
    -addext "subjectAltName=DNS:gitlab" \ # <1>
    -subj "/C=DE/ST=DE/L=DE/O=unexist.dev/OU=showcase/CN=gitlab" # <2>
----
<1> This line is essential, otherwise Gitlab won't accept this cert
<2> We are going to use *gitlab* for the hostname, so make sure to add it to your hosts file

==== Starting Gitlab

Next up is the actual config of Gitlab.
There is plenty of stuff that can actually be configured, especially in
[constrained environments][] it is beneficial to disable services like [Prometheus][], but this
excerpt includes only the bare minimum to run Gitlab.

[source,ruby]
----
external_url 'https://gitlab:10443/'
registry_external_url 'https://gitlab:4567' # <1>

registry_nginx['enable'] = true
registry_nginx['listen_port'] = 4567 # <2>

nginx['ssl_certificate'] = "/etc/gitlab/ssl/gitlab.crt"
nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/gitlab.key"
nginx['listen_port'] = 10443 # <3>
----
<1> Setting the ports here cases problems elsewhere, so better also set the ports in <2> and <3>
<2> My initial idea was to use the registry as a cache, but more to that later
<3> Nginx usually picks the port from _external_url_, which is not what we want to do

Almost there.
Like [Kubernetes][] Podman allows to group or rather encapsulate container
in [pods][] and also to convert them afterwards, so let us quickly create one:

[source,shell]
----
$ podman pod create -n gitlab --network bridge \
    -p 10022:22 -p 10080:80 -p 10443:10443 \
    -p 4567:4567
991e7a69b59e76e051d87ef756169c9ed53e4b4090650a0e41cd09cf6ffd7eb9
----

TIP: This can be done with the make target `pd-pod-create`.

And with everything in place we can fire up Gitlab:

[source,shell]
----
$ podman run -dit --name gitlab --pod=gitlab \
    --memory=4096m --cpus=4 \
    -v ./gitlab.crt:/etc/gitlab/ssl/gitlab.crt \ # <1>
    -v ./gitlab.key:/etc/gitlab/ssl/gitlab.key \
    -v ./gitlab.rb:/etc/gitlab/gitlab.rb \ # <2>
    -v ./gitlab-data:/var/opt/gitlab \
    -e GITLAB_ROOT_EMAIL=admin@local -e GITLAB_ROOT_PASSWORD=YourPassword \ #<3>
    docker.io/gitlab/gitlab-ce:latest
17349b87f81aa9eb7230f414923cf491c84a36a87d61057f8dc2f8f82c7ea60a
----
<1> We pass our new certs via volume mounts to Gitlab
<2> Our previously modified minimal config
<3> Let us be creative

TIP: This can also be done with the make target `pd-gitlab`.

==== Starting a runner

Following commands are required to start the required containers:

==== Summing up

Once everything is ready `podman ps` should show following:

[source,shell]
----
$ podman ps -a --format 'table {{.ID}} {{.Image}} {{.Status}} {{.Names}}'
CONTAINER ID  IMAGE                                  STATUS                       NAMES
09ef2665fb09  localhost/podman-pause:4.3.1-0         Up 2 hours ago               991e7a69b59e-infra
ccae50ee7749  docker.io/gitlab/gitlab-runner:latest  Up 2 hours ago               runner
e88fcb56c786  docker.io/gitlab/gitlab-ce:latest      Up 17 minutes ago (healthy)  gitlab
----

The webinterface can be reached at following address:
<https://localhost:10443>

=== Register the runner

Due to the new registration process of Gitlab v16.x tokens are obsolete and the registration must be
started inside Gitlab via `New instance runner` at:
<https://localhost:10443/admin/runners>

[source,shell]
----
$ gitlab-runner register  --url https://gitlab:443  --token glrt-6kixPTKGk5XLf-QLbdUF
Runtime platform                                    arch=amd64 os=linux pid=97 revision=81ab07f6 version=16.10.0
Running in system-mode.

Enter the GitLab instance URL (for example, https://gitlab.com/):
[https://gitlab:443]:
Verifying runner... is valid                        runner=6kixPTKGk
Enter a name for the runner. This is stored only in the local config.toml file:
[showcase]:
Enter an executor: custom, docker+machine, docker-autoscaler, virtualbox, docker, docker-windows, kubernetes, instance, shell, ssh, parallels:
docker
Enter the default Docker image (for example, ruby:2.7):
quay.io/podman/stable
Runner registered successfully. Feel free to start it, but if it's running already the config should be automatically reloaded!

Configuration (with the authentication token) was saved in "/etc/gitlab-runner/config.toml"
----

== Conclusion

All examples can be found here:

<https://github.com/unexist/showcase-dagger-golang>
