---
layout: post
title: Gluecode?
date: %%%DATE%%%
last_updated: %%%DATE%%%
author: Christoph Kappel
tags: cucumber karate showcase
categories: testing bdd showcase
toc: true
---
:imagesdir: /assets/images/gluecode.adoc

[Acceptance testing][] is one of the things I am highly interested in and if you browse through the
posts of this blog you are going to find one or another post about the whole idea, some
noteworthy tools and of course, reporting.

One aspect I barely touched so far is how do we bring the actual behavioral tests and the
[system under test][] (SUT) together?

I'd say with glue - but let us set the stage first and talk about what we going to do.

== Set the stage

The general idea of [behavior-driven design][] is to consider a software component as a
**blackbox** and describe (and later verify) the observable behavior without any knowledge of
its internal workings or the chosen technology - this is in contrast to other tests, which use
a **whiebox** approach.

That's the theory, let us apply this to an example.

== Use case: Create a todo

My showcases usually follow an overarching scheme - so if you haven't seen one of them you can
basically expect the same simple application in each of them.

This simple application provides a [REST][] endpoint to create todo entries and also offers some
other methods of interacting with them.

The first use case we are going to look into is the creation of the entries by passing a `title`
and a `description` over to our endpoint and verify if we somehow receive the `id` of the newly
created entry.

CAUTION: Here we assume the id is related to the domain and not technically at all.

[source,gherkin]
----
Feature: Create a todo

  Scenario Outline: Create a todo with title and description and check the id.
    Given I create a todo
    When its title is "<title>"
    And its description is "<description>"
    Then its id should be <id>

    Examples:
      | title  | description  | id |
      | title1 | description1 | 1  |
      | title2 | description2 | 2  |
----

I think the example above speaks for itself:
It uses [Gherkin][] to create a natural language and allows some niceties like example tables in
a really easy format.

Here we stumble upon our first problem - how do we actually verify, if our request succeeded?
It is time for the glue now!

== Where is the glue?

[Gluecode][] is basically every line of code, that is required to combine the [Gherkin][] code from
above in a meaningful way with our software.

The [JVM bindings][] provide annotations, which can be used to define handling methods for the
keywords.

[source,java]
----
public class TodoSteps {
    private final DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    private RequestSpecification requestSpec;
    private TodoBase todoBase;
    private DueDate dueDate;

    @Before
    public void beforeScenario() {
        this.requestSpec = new RequestSpecBuilder()
                .setPort(8081)
                .setContentType(ContentType.JSON)
                .setAccept(ContentType.JSON)
                .build();
    }

    @Given("I create a todo")
    public void given_create_todo() {
        this.todoBase = new TodoBase();
        this.dueDate = new DueDate();
    }

    @When("its title is {string}")
    public void when_set_title(String title) {
        this.todoBase.setTitle(title);
    }

    @And("its description is {string}")
    public void and_set_description(String description) {
        this.todoBase.setDescription(description);
    }

    @Then("its id should be {int}")
    public void then_get_id(int id) {
        String location = given(this.requestSpec)
            .when()
                .body(this.todoBase)
                .post("/todo")
            .then()
                .statusCode(201)
            .and()
                .extract().header("location");

        assertThat(location.substring(location.lastIndexOf("/") + 1))
                .isEqualTo(Integer.toString(id));
    }
}
----


[source,gherkin]
----
  Scenario Outline: Create a todo with start and due dates and check the status.
    Given I create a todo
    When it starts on "<start>"
    And it ends on "<due>"
    Then it should be marked as <status>

    Examples:
      | start      | due        | status  |
      | 2021-09-10 | 2022-09-10 | undone  |
      | 2021-09-10 | 2021-09-09 | done    |
----

[source,java]
----
public class TodoSteps {
    private final DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    private RequestSpecification requestSpec;
    private TodoBase todoBase;
    private DueDate dueDate;

    @Before
    public void beforeScenario() {
        this.requestSpec = new RequestSpecBuilder()
                .setPort(8081)
                .setContentType(ContentType.JSON)
                .setAccept(ContentType.JSON)
                .build();
    }

    @Given("I create a todo")
    public void given_create_todo() {
        this.todoBase = new TodoBase();
        this.dueDate = new DueDate();
    }

    /* Scenario 1 */

    @When("its title is {string}")
    public void when_set_title(String title) {
        this.todoBase.setTitle(title);
    }

    @And("its description is {string}")
    public void and_set_description(String description) {
        this.todoBase.setDescription(description);
    }

    @Then("its id should be {int}")
    public void then_get_id(int id) {
        String location = given(this.requestSpec)
            .when()
                .body(this.todoBase)
                .post("/todo")
            .then()
                .statusCode(201)
            .and()
                .extract().header("location");

        assertThat(location.substring(location.lastIndexOf("/") + 1))
                .isEqualTo(Integer.toString(id));
    }

    /* Scenario 2 */

    @When("it starts on {string}")
    public void when_set_start_date(String datestr) {
        if (StringUtils.isNotEmpty(datestr)) {
            this.dueDate.setStart(LocalDate.parse(datestr, this.dtf));
        }
    }

    @And("it ends on {string}")
    public void and_set_due_date(String datestr) {
        if (StringUtils.isNotEmpty(datestr)) {
            this.dueDate.setDue(LocalDate.parse(datestr, this.dtf));
        }
    }

    @Then("it should be marked as {status}")
    public void then_get_status(boolean status) {
        this.todoBase.setDueDate(this.dueDate);

        assertThat(status).isEqualTo(this.todoBase.getDone());
    }

    @ParameterType("done|undone")
    public boolean status(String status) {
        return "done".equalsIgnoreCase(status);
    }
}
----

== Karate

[source,gherkin]
----
Feature: Create a todo

  Background:
    * url 'http://localhost:8081'

  Scenario Outline: Create a todo with title and description and check the id.
    Given path 'todo'
    And request
    """
    {
      "description": <description>,
      "done": true,
      "dueDate": {
        "due": "2021-05-07",
        "start": "2021-05-07"
      },
      "title": <title>
    }
    """
    When method post
    Then match header location ==  "#regex .*/todo/<id>"

    Examples:
      | title    | description    | id |
      | 'title1' | 'description1' | 1  |
      | 'title2' | 'description2' | 2  |
----

[source,gherkin]
----
  Scenario Outline: Create a todo with start and due dates and check the status.
    Given def createTodo =
    """
    function(args) {
      var TodoType = Java.type("dev.unexist.showcase.todo.domain.todo.Todo");
      var DueDateType = Java.type("dev.unexist.showcase.todo.domain.todo.DueDate");
      var DateTimeFormatterType = Java.type("java.time.format.DateTimeFormatter");
      var LocalDateType = Java.type("java.time.LocalDate");

      var dtf = DateTimeFormatterType.ofPattern("yyyy-MM-dd");

      var dueDate = new DueDateType();

      dueDate.setStart(LocalDateType.parse(args.startDate, dtf));
      dueDate.setDue(LocalDateType.parse(args.dueDate, dtf));

      var todo = new TodoType();

      todo.setDueDate(dueDate);

      return todo.getDone() ? "done" : "undone";
    }
    """
    When def result = call createTodo { startDate: <start>, dueDate: <due> }
    Then match result == "<status>"

    Examples:
      | start      | due        | status |
      | 2021-09-10 | 2022-09-10 | undone |
      | 2021-09-10 | 2021-09-09 | done   |
----

[source,java]
----
public class TodoKarateFixture {

    @Karate.Test
    Karate shouldValidateTodo() {
        return Karate.run("todo").relativeTo(getClass());
    }
}
----

[source,log]
----
01: undone
<<<<
org.graalvm.polyglot.PolyglotException: ReferenceError: "undone" is not defined
- <js>.:program(Unnamed:1)

classpath:dev/unexist/showcase/todo/domain/todo/todo.feature:52
2022-08-31 14:47:33,699 WARNING [org.jun.pla.lau.cor.CompositeTestExecutionListener] (main) TestExecutionListener [org.apache.maven.surefire.junitplatform.RunListenerAdapter] threw exception for method: executionFinished(TestIdentifier [uniqueId = [engine:junit-platform-suite]/[suite:dev.unexist.showcase.todo.TestSuite]/[engine:junit-jupiter]/[class:dev.unexist.showcase.todo.domain.todo.TodoKarateFixture]/[test-factory:shouldValidateTodo()]/[dynamic-container:#1]/[dynamic-test:#3], parentId = [engine:junit-platform-suite]/[suite:dev.unexist.showcase.todo.TestSuite]/[engine:junit-jupiter]/[class:dev.unexist.showcase.todo.domain.todo.TodoKarateFixture]/[test-factory:shouldValidateTodo()]/[dynamic-container:#1], displayName = '[2.1:56] Create a todo with start and due dates and check the status.', legacyReportingName = 'shouldValidateTodo()[1][3]', source = FileSource [file = /Users/christoph.kappel/Projects/showcase-acceptance-testing-quarkus/todo-service-karate/target/test-classes/dev/unexist/showcase/todo/domain/todo/todo.feature, filePosition = FilePosition [line = 56, column = -1]], tags = [], type = TEST], TestExecutionResult [status = FAILED, throwable = org.opentest4j.AssertionFailedError: js failed:
>>>>
----

== Conclusion

I've added all the mentioned [Karate][] examples to my acceptance testing showcase and you can find
it in the usual place:

<https://github.com/unexist/showcase-acceptance-testing-quarkus>