---
layout: post
title: Message formats and versioning
date: %%%DATE%%%
last_updated: %%%DATE%%%
author: Christoph Kappel
tags: showcase
categories: kafka avro apicurio karapace showcase
toc: true
---
:imagesdir: /assets/images/message-formats-and-versioning.adoc

When you send a letter to someone else it probably helps, when all participants of this exchange
speak the same language and it can't be wrong, when the format of the letter is something all sides
can handle safely.
Obviously, the same is true for inter-service-communication, but unlike snail mail the message
format will most likely change over time.

In this article we take a closer look at message formats and versioning and talk about ways
to handle this situation.

== Message formats

Nobody quite right on his mind would pick [JSON][] for a letter exchange, but for messaging between
services it is quite common:

[source,json]
----
{"title":"First","description":"Bla","done":null,"dueDate":null,"id":0}
----

This format is straight forward and modern JSON parsers are mature enough to handle `NULL` values
in any direction, so when something is unset it doesn't bother us and also when something required
is missing it can point us to the problem.

== Versioning