---
layout: post
title: Message formats and versioning
date: %%%DATE%%%
last_updated: %%%DATE%%%
author: Christoph Kappel
tags: showcase
categories: kafka avro apicurio karapace showcase
toc: true
---
:imagesdir: /assets/images/message-formats-and-versioning.adoc

When you send a letter to someone else it probably helps, when all participants of this exchange
speak the same language and it can't be wrong, when the format of the letter is something all sides
can handle safely.
Obviously, the same is true for inter-service-communication, but unlike snail mail the message
format will most likely change over time.

In this article we take a closer look at message formats, versioning and talk about ways
to handle these situations.

== Message formats

Nobody in their right mind would pick [JSON][] for a letter exchange, but for messaging between
services it is quite common:

[source,json]
----
{
    "title": "First",
    "description": "Bla",
    "done": null,
    "dueDate": "2022-11-21",
    "id": 0
}
----

This format is straight forward and modern JSON parsers are mature enough to handle `NULL` values
in any direction.
So when something optional is unset we aren't bothered and on the other hand when something is amiss
we are gracefully pointed to the problem.

There normally shouldn't be any surprises waiting for us - until we do something like this:

[source,json]
----
{
    "title": "First",
    "description": "Bla",
    "done": null,
    "dueDate": {
        "startDate": "2022-11-20",
        "dueDate": "2022-11-21"
    },
    "id":0
}
----

Here we evolve our `dueDate` field to accept a **start** and a **due** date and this change is
quite incompatible to the predecessor.

At this point nothing stops us from building a mapping layer in-between, but please put that
thought aside and follow me to the next chapter.

== Versioning

Found your way?
Great - so we probably agree the obvious solution to our problem is versioning but what exactly -
the endpoint itself or rather our message?

Let us consider both.

=== Endpoint versioning

