---
layout: post
title: OpenAPI and AsciiDoc in the Mix
description: This blog post explains how documentation from Doxygen and AsciiDoc can be brought together with the help of AsciiDoxy.
#date: %%%DATE%%%
#last_updated: %%%DATE%%%
author: Christoph Kappel
tags: asciidoc openapi asciidoxy kotlin showcase
categories: documentation myself
toc: true
---
ifdef::asciidoctorconfigdir[]
:imagesdir: {asciidoctorconfigdir}/../assets/images/openapi_and_asciidoc_in_the_mix
endif::[]
ifndef::asciidoctorconfigdir[]
:imagesdir: /assets/images/openapi_and_asciidoc_in_the_mix
endif::[]
:figure-caption!:
:table-caption!:

////
https://github.com/SMILEY4/ktor-openapi-tools
https://github.com/Redocly/redoc
https://swagger.io/tools/swagger-ui/
https://github.com/joensson/swagger2asciidoc
https://openapi-generator.tech/
////

I am getting more and more obsessed with centralized documentation and this isn't because I enjoy
writing documentation (which I unfortunately really do), but more due sheer lack of it in my day
job and all the related issues we are currently facing.

Pushing ideas like the one from my previous post
({{ site.url }}{% post_url 2024-12-26-bringing-documentation-together %}[Bringing documentation together])
certainly helps to make writing docs easier, but are still some loose ends to follow - like API.

So this post is going to demonstrate how [OpenAPI][] (or formerly [Swagger][]) can be converted
into shiny [AsciiDoc][] and be brought into the mix.

== Why OpenAPI?

There are many ways to document API (mind you any documentation is better than none!), but keeping
established standards like [OpenAPI][] and [AsyncAPI][] (which isn't to far off) really help to
keep the cognitive churn low while trying to understand what a document is trying to convey.

And from a developer's perspective there are many low-hanging fruits:

- Code-first or API-first - you decide
- Many generators in both directions available - like [ktor-openapi-tools][] used in the example
- Tools like [Swagger UI][] and [Redoc][]
- Comes pre-assembled with a testing tool

TIP: Still not sold? <https://swagger.io/blog/api-strategy/benefits-of-openapi-api-development/>

== Converting to AsciiDoc

Again, there are dozens of options to select from and some of them stopped working sanely years
ago.
Since I rely on the [confluence publisher plugin][] my initial pick was another
[Maven][]-integration - [swagger2asciidoc][].
Unfortunately the project is unmaintained for quite some time and relies on obscure and ancient
packages and are kind of educative what happens on outdated package mirrors.

The next best option and probably should be the first address anyway are the generators of the
OpenAPI project.

== Conclusion

All examples can be found here:

<https://github.com/unexist/showcase-openapi-asciidoc>
