---
layout: post
title: Playing with OData
description: This blog introduces OData and summarizes the main similarities and differences between itself and plain REST.
#date: %%%DATE%%%
#last_updated: %%%DATE%%%
author: Christoph Kappel
tags: showcase
categories: tech
toc: true
---
ifdef::asciidoctorconfigdir[]
:imagesdir: {asciidoctorconfigdir}/../assets/images/playing_with_odata
endif::[]
ifndef::asciidoctorconfigdir[]
:imagesdir: /assets/images/playing_with_odata
endif::[]
:figure-caption!:
:table-caption!:

////
https://www.sap.com/products/technology-platform.html
https://olingo.apache.org/
https://www.mydbsync.com/blogs/odata-and-rest-apis-a-comparison
https://restfulapi.net/
////

Last year I briefly dived into the world of [SAP][] and its new [Business Technology Platform][]
(BTP) and tried to make sense of everything there.
During that time I discovered [OData][] or Open Data protocol is the communication protocol by
choice and wondered why it is favored over traditional [REST][].

So during the course of this blog post we are going to have a look at the main differences of
both and also at a rudimentary implementation based on the projects [Apache Olingo][] and our
good fellow [Quarkus][].

Before we can actually start to compare both, let us quickly recap what REST actually is.

== What is REST?

[Represental State Transfer][] or REST is an architecture style based on doctoral thesis by
[Roy Fielding].

He defined a set of six easy principles, properties and constraintrs for easy communication between
web services:

|====
| *Uniform interface* | Interfaces must be unique identifiable, self-descriptive and have a uniform representation
| *Client-Server* | Separation of concern allows client and server to evolve independently
| *Stateless* | Each request must contain all the necessary information to handle it
| *Cachable* | A response can be re-used or marked as non-cachable
| *Layered System* | Hierarchical layers
| *Code on demand* (optional) | Client functionality can be extended by downloading and executing scripts or applets
|====

== And what is OData?

=== Metadata

=== Query, Filter, Expand

== Conclusion

All examples can be found here:

<https://github.com/unexist/showcase-odata-quarkus>