---
layout: post
title: Rewriting in Rust
description: TBD
#date: %%%DATE%%%
#last_updated: %%%DATE%%%
author: Christoph Kappel
tags: rust subtle clean-code showcase
categories: tech
toc: true
---
ifdef::asciidoctorconfigdir[]
:imagesdir: {asciidoctorconfigdir}/../assets/images/rewriting_in_rust
endif::[]
ifndef::asciidoctorconfigdir[]
:imagesdir: /assets/images/rewriting_in_rust
endif::[]
:figure-caption!:
:table-caption!:

:rust: https://rust-lang.org/
:windowmanager: https://en.wikipedia.org/wiki/Window_manager
:subtle: https://subtle.de/
:20years: https://hg.unexist.dev/subtle/rev/40917ee3b688
:subtle-rs: https://subtle.rs/
:ai: https://en.wikipedia.org/wiki/Artificial_intelligence
:c2rust: https://github.com/immunant/c2rust
:legacycheck: https://understandlegacycode.com/blog/what-is-legacy-code-is-it-code-without-tests/
:x11: https://en.wikipedia.org/wiki/X_Window_System
:wayland: https://en.wikipedia.org/wiki/Wayland_(protocol)
:gnomex11: https://blogs.gnome.org/alatiera/2025/06/23/x11-session-removal-faq/

During my career facing legacy code has always been an annoying task and it took me quite some
years to understand, that oftentimes today's code is tomorrow's legacy.
Still, legacy code can be a great opportunity to learn something new and especially when you are
the original author of the piece.

This post jumps on the bandwagon of rewriting everything in {rust}[Rust] and elaborates a bit on my
personal motivation and learnings of rewriting my pet {windowmanager}[window manager] project
{subtle}[subtle], which I started {20years}[~20 years]footnote:[The first commit is actually a bit
older, but apparently moving from CVS > SVN > HG isn't frictionless] ago and still use it on a
daily basis.

== Why?

Among the many things {ai}[AI] can _do for us_, migrating code from one language into another is
usually a strong selling point and even without AI there are excellent tools on its own, like
{c2rust}[C2Rust], to get the job done with just a flick of a finger.

So why is an excellent question.

One of my main motivators isn't just to get the job done, like I lamented on a bit in my
{{ site.url }}{% post_url 2025-09-22-fear_of_missing_out_on_ai %}[previous blog post], but to have
a learning experience and take something from it besides another code base, which easily ticks
every point of the {legacycheck}[legacy code checklist].

Manual labor isn't probably the most controversial aspect of it, but porting an {x11}[X11]
application in the [line-through]#day# [line-through]#year# epoch of {wayland}[Wayland] might look
like a waste of time.

Alas, the reasoning here is basically the same.
I've spend many years with X11 and learning its core concepts and still like the system and
capabilities.
Additionally I am not entirely certain there is a giant switch to get rid of it, despite how
decisions of e.g. the {gnomex11}[GNOME project]footnote:[GNOME and I had some intermezzos back
then, but that is more than a decade ago] might appear.

Convincing so far?
If not let me know, if not please also feel free.

== Learnings so far

=== God objects

=== Borrow checker

=== Interior mutability

=== Explicit copies

== Conclusion

All examples can be found here:

<https://github.com/unexist/subtle-rs>
