---
layout: post
title: Writing architecture documentation
description: This blog post illustrates how C4-based architecture documentation can be derived from a simple model with the help of Struturizr.
#date: %%%DATE%%%
#last_updated: %%%DATE%%%
author: Christoph Kappel
tags: golang c4 structurizr showcase
categories: architecture
toc: true
---
ifdef::asciidoctorconfigdir[]
:imagesdir: {asciidoctorconfigdir}/../assets/images/writing_architecture_documentation
endif::[]
ifndef::asciidoctorconfigdir[]
:imagesdir: /assets/images/writing_architecture_documentation
endif::[]
:figure-caption!:
:table-caption!:
:page-liquid:

[quote,Dick Brandon]
Documentation is like sex: when it is good, it is very, very good; and when it is bad, it is
better than nothing.

Got your attention? Alright!

Writing documentation is rarely a welcome task and most of the time the thing that should be
documented is in a state that rather justifies a re-write than many hours of labor to document it.
Still, when you stumble upon a new code base every bit of documentation can help and save some
headaches.

Usually tests are the best type of documentation for behaviour, but unfortunately this doesn't
apply to architectures.
So in this blog post we are going to have a look at [Struturizr][] and check
different ways of building up our model which can be used to create [C4][] views:

. Creating the model manually
. Scraping code with [go-structurizr][]
. Using a domain-specific language with [goadesign][]

[TIP]
====
Everything is again based on our well-known [Todo-application][] basically used in every other
post of this blog.
====

== Introduction time

There are many ways to create software architecture diagrams and most of them heavily utilize
[UML][], which can be difficult to write and later read for the targeted audience.

Struturizr follows a slightly different approach and provides its own sets of elements and
relationships to establish a simple model.
Once defined this model can be used to extract different views like the [system context][] to see
an overview of the system, its neighbours and actors or the [container view][] to basically list
all deployable units.

Both views are part of the [C4][] model and represent the first two of the four parts of the model.
The remaining ones are the [component diagram][] and the [code diagram][] which provide further
more fine grained details of container internals respective the structure of the actual code base.

== Creating the model manually

[source,text]
----
workspace {
    model {
        user = person "User"
        softwareSystem = softwareSystem "Software System" {
            frontend = container "Web Frontend" {
                user -> this "Uses"
            }
            backend = container "Web API" {
                frontend -> this "Makes API calls to"
            }
            container "Database" {
                backend -> this "Reads from and writes to"
            }
        }
    }

    views {
        systemContext softwareSystem {
            include *
            autolayout lr
        }

        container softwareSystem {
            include *
            autolayout lr
        }

        theme default
    }
}
----

=== System context

++++
{% plantuml %}
!theme unexist from {{ site.asciidoctor_attributes.plantumldir }}
set separator none
title Software System - System Context

left to right direction

!include <C4/C4>
!include <C4/C4_Context>

Person(User, "User", $descr="", $tags="", $link="")
System(SoftwareSystem, "Software System", $descr="", $tags="", $link="")

Rel(User, SoftwareSystem, "Uses", $techn="", $tags="", $link="")
{% endplantuml %}
++++

=== Container view

++++
{% plantuml %}
!theme unexist from {{ site.asciidoctor_attributes.plantumldir }}
set separator none
title Software System - Containers

left to right direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

Person(User, "User", $descr="", $tags="", $link="")

System_Boundary("SoftwareSystem_boundary", "Software System", $tags="") {
  Container(SoftwareSystem.WebFrontend, "Web Frontend", $techn="", $descr="", $tags="", $link="")
  Container(SoftwareSystem.WebAPI, "Web API", $techn="", $descr="", $tags="", $link="")
  Container(SoftwareSystem.Database, "Database", $techn="", $descr="", $tags="", $link="")
}

Rel(User, SoftwareSystem.WebFrontend, "Uses", $techn="", $tags="", $link="")
Rel(SoftwareSystem.WebFrontend, SoftwareSystem.WebAPI, "Makes API calls to", $techn="", $tags="", $link="")
Rel(SoftwareSystem.WebAPI, SoftwareSystem.Database, "Reads from and writes to", $techn="", $tags="", $link="")
{% endplantuml %}
++++

== Scraping the code

As the name probably implies Go-structurizr is based on Structurizr and allows to create a single model and used it to create
different kind and levels of diagrams.


[source,yaml]
----
configuration:
    title: Test
    pkgs:
        - "github.com"

rules:
    -   name_regexp: ".*"
        pkg_regexps:
            - ".*/adapter"
        component:
            description: "adapter component"
            tags:
                - ADAPTER
----

[source,yaml]
----
view:
    title: Todo service components
    line_color: 000000ff
    styles:
        -   id: ADAPTER
            background_color: 2d69b7ff
            font_color: ffffffff
            border_color: 000000ff
            shape: artifact
    root_component_tags:
        - ADAPTER
    component_tags:
        - ADAPTER
----

Once both configs are set we can write the actual program:

[source,go]
----
func main() {
	scraper, err := structScaper.NewScraperFromConfigFile("scraper.yaml") // <1>
	if err != nil {
		panic(err)
	}

	/* Create business stuff */
	var todoRepository *infrastructure.TodoFakeRepository

	todoRepository = infrastructure.NewTodoFakeRepository()

	defer todoRepository.Close()

	todoService := domain.NewTodoService(todoRepository)
	todoResource := adapter.NewTodoResource(todoService)

	structure := scraper.Scrape(todoResource) // <2>

	view, err := structView.NewViewFromConfigFile("view.yaml") // <3>
	if err != nil {
		panic(err)
	}

	outFile, err := os.Create("c4.plantuml")
	if err != nil {
		panic(err)
	}
	defer outFile.Close()

	err = view.RenderStructureTo(structure, outFile) // <4>
	if err != nil {
		panic(err)
	}
}
----
<1> This instructs the scraper which packages are interesting and how they should be tagged
<2> The scraper does whatever a scraper does
<3> Here we source the styling informationen of the diagram
<4> And finally the output file is rendered to disk

The final output looks like this - depending on the [Grahpviz][] gods your mileage
may vary:

++++
{% plantuml %}
!theme unexist from {{ site.asciidoctor_attributes.plantumldir }}
title Service components

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
top to bottom direction

skinparam rectangle<<_GROUP>> {
  FontColor #ffffff
  BorderColor #ffffff
}

skinparam artifact<<ADAPTER>> {
  BackgroundColor #2d69b7
  FontColor #ffffff
  BorderColor #000000
}

skinparam usecase<<DOMAIN>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #000000
}

skinparam database<<INFRASTRUCTURE>> {
  BackgroundColor #c8c8c8
  FontColor #000000
  BorderColor #000000
}

rectangle 0ADAPTER <<_GROUP>> {
	artifact "==adapter.TodoResource\n<size:10>[component]</size>\n\nadapter component" <<ADAPTER>> as 3081293365
}
rectangle 30812933651DOMAIN <<_GROUP>> {
	usecase "==domain.TodoService\n<size:10>[component]</size>\n\ndomain component" <<DOMAIN>> as 2425084387
}
3081293365 .[#000000].> 2425084387 : ""
rectangle 24250843872INFRASTRUCTURE <<_GROUP>> {
	database "==infrastructure.TodoFakeRepository\n<size:10>[component]</size>\n\ninfrastructure component" <<INFRASTRUCTURE>> as 2184463684
}
2425084387 .[#000000].> 2184463684 : ""
rectangle 24250843872DOMAIN <<_GROUP>> {
	usecase "==domain.Todo\n<size:10>[component]</size>\n\ndomain component" <<DOMAIN>> as 542314480
}
2425084387 .[#000000].> 542314480 : ""
2184463684 .[#000000].> 542314480 : ""
{% endplantuml %}
++++

== Using a domain-specific language

[source,go]
----
var _ = Design("Todo design", "This is a design of the todo service", func() {
	Version("0.1")
	Enterprise("Todo Showcase Service")

	var system = SoftwareSystem("Software System", "The todo software system", func() {
		Tag("system")
		URL("https://unexist.blog")

		container_webserver = Container("Webserver", "A webserver to deliver the frontend", "Nginx", func() {
			Tag("infrastructure")
			URL("https://nginx.org/")
		})

		container_frontend = Container("Web Frontend", "A Angular-based web frontend", "Angular + REST", func() {
			Tag("frontend")

			Uses("Webserver", "Is delivered by", "HTTP", Asynchronous)
			Uses("Web API", "Makes API calls to", "HTTP", Asynchronous)
		})

		container_backend = Container("Web API", "A backend service", "GinTonic + REST", func() {
			Tag("backend")

			Uses("Database", "Reads from and writes to", "SQL/TCP", Asynchronous)

			Component("Todo Service", "Domain logic for todo", "Golang", func() {
				Tag("service")
			})
		})

		Container("Database", "A RDBMS to handle the data", "Postgresql", func() {
			Tag("infrastructure")
			URL("https://postgresql.org")
		})
	})

	DeploymentEnvironment("Dev", func() {
		DeploymentNode("Cloud", func() {
			ContainerInstance("Software System/Webserver")
			ContainerInstance("Software System/Web Frontend")
			ContainerInstance("Software System/Web API")
			ContainerInstance("Software System/Database")
		})
	})

	Person("User", "A user of the software system.", func() {
		Tag("person")

		Uses(system, "Uses")
		Uses("Software System/Web Frontend", "Creates, views, edits and delete todos using", "HTTP", Asynchronous)
	})

	Views(func() {
		SystemLandscapeView("SystemLandscapeView", "A System Landscape View", func() {
			Title("Overview of the system landscape")
			AddAll()
			AutoLayout(RankLeftRight)
		})

		SystemContextView(system, "SystemContext", "A System Context diagram.", func() {
			Title("Overview of the system")
			AddAll()
			AutoLayout(RankLeftRight)
		})

		ContainerView(system, "ContainerView", "A Container View", func() {
			Title("Overview of the containers")
			AddAll()
			AutoLayout(RankLeftRight)
		})

		ComponentView(container_frontend, "ComponentView Frontend", "A Component View of the web frontend", func() {
			Title("Overview of the frontend components")
			AddComponents()
			AutoLayout(RankLeftRight)
		})

		ComponentView(container_backend, "ComponentView Backend", "A Component View of the web backend", func() {
			Title("Overview of the backend components")
			AddComponents()
			AutoLayout(RankLeftRight)
		})

		DeploymentView(Global, "Dev", "deployment", "A Deployment View", func() {
			Title("Overview of the deployment on Dev")
			AddAll()
			AutoLayout(RankLeftRight)
		})

		Styles(func() {
			ElementStyle("infrastructure", func() {
				Shape(ShapeComponent)
				Background("#1168bd")
				Color("#ffffff")
			})
		})
	})
})
----

== Conclusion

All examples can be found here:

<https://github.com/unexist/showcase-architecture-documentation>